services:
  dropdroid:
    image: cr.enginecrafter77.dev/enginecrafter77/dropdroid-server:latest
    command: /app/dropdroid -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.cors=true -Dquarkus.http.cors.origins=* -Dquarkus.http.cors.access-control-allow-credentials=true
    mem_limit: 128M
    ports:
     - "8080:8080"
    volumes:
     - "dropdroid:/dropdroid"

volumes:
  dropdroid:
    name: "dropdroid-server"
