services:
  dropdroid:
    container_name: dropdroid
    image: cr.enginecrafter77.dev/enginecrafter77/dropdroid-server:2.0.x
    mem_limit: 128M
    environment:
      QUARKUS_HTTP_CORS_ORIGINS: '*'
    ports:
     - "8080:8080"
    volumes:
     - "dropdroid:/dropdroid"

volumes:
  dropdroid:
    name: "dropdroid-server"
